[package]
name = "repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast ={ path = "../ast" }
color-eyre = "0.6.2"
whoami = "1.5.1"
